### PR TITLE
Hotfix/name change update only

### PR DESCRIPTION
**Pull request by conitrade-as**
These two commits should fix all cases I could imagine. May be there are more cases people can think of?

I tried several upgrade paths to the newest version (all 64bit on Windows 10). So far all has worked out.

### CODE REVIEW

**Comment by conitrade-as** [comment]
@aledeniz Can you give this a try?

**Comment by aledeniz** [comment]
@conitrade-as I have re-packaged my internal adobereader package with this, I have tried it in 1 computer, it did work, but it is asking a restart. I am not sure if it is specific to that given computer, I have asked a colleague if they could continue to test it on other computers, I may get their feedback during the day.
Interestingly, we have noticed that in some computers with the DisplayName "Adobe Acrobat (64-bit)" this seems to be able to upgrade both Acrobat Reader and the full fledged Acrobat. Actually, in those computers we only have 1 installed product, acting either as Acrobat Reader either as Acrobat, depending from the user licensing.

**Comment by aledeniz** [comment]
@conitrade-as my colleague never reported back, they were likely busy with some other workstream. I checked our reports, roughly 55 computers were updated, of those likely 20-25 with this patch, I haven't received any negative feedback so far.
Caveat: our environments aren't very heterogeneous, we keep the version distribution as small as feasible, and very skewed towards the most recent version, in other words it is not exactly the ideal testing environment for a package such as this.

**Comment by aledeniz** [comment]
@conitrade-as with a colleague we have pushed successfully this patch to around 600 machines.

**Comment by conitrade-as** [comment]
I guess that makes #36 obsolete then? @sbaerlocher Can you proceed with merging and push a new release if you feel comfortable with this change?

**Comment by aledeniz** [comment]
I have closed #36. The two PRs do the same thing, #37 is more in line with the rest of the package.

**Comment by pauby** [comment]
Are we able to move this PR forward to get merged so that the package can be updated? @sbaerlocher has been pinged on both this PR and the related issue but has not added any updates. Can we move forward without him?

**Comment by pauby** [comment]
@olifre I'm following up from my previous comment. Can we move forward with this and get a fixed version pushed?

**Comment by aledeniz** [comment]
Today Adobe released a new version (23.003.20215.0). I downloaded it (the 2 msp files), I repackaged internally this package with this PR and I pushed it to 100 computers (a mix of servers and clients).
97% success rate.
The 3 where it didn't work: 1 was having no space on the OS drive, the other 2 were unreachable.

**Comment by pauby** [comment]
@aledeniz That's a huge tick in the box for it working! Thanks for trying it and confirming the results.

**Comment by olifre** [comment]
> @olifre I'm following up from my previous comment. Can we move forward with this and get a fixed version pushed?

@pauby I don't have any permissions on this repository and am not affiliated with Open Circle AG; I'm just a technically versed Chocolatey user myself, so I'm sorry that I can't help out :cry: .

**Comment by pauby** [comment]
@olifre Thanks for letting me know. I appreciate it.

I'm genuinely having a difficult time with this one. I would rather not seem as if I'm pressuring maintainers, as I am most definitely not — I appreciate everything the Chocolatey Community and the maintainers do. But at the same time, we have a PR that has many comments, but no traction to get it merged. So, we're stuck.

As a maintainer who picked this up just to resolve the problems with the package, I feel like we need to move forward and get this fixed up. If there is no progress on the PR _this week_, I'll pick the package up, fix it and push a new version. I'll then ask the community packages repository maintainers if they would pick it up and move it there. To achieve this, I will need to remove the other maintainers from the [package](https://community.chocolatey.org/packages/adobereader) so that their automation doesn't kick in, and we have two automations pushing packages.

This is the last resort, and I'm very reluctant to do this. I can't see any other option at the moment. Outside of @sbaerlocher, I don't know anybody else to tag to get their attention. If anybody else does know, please add a comment tagging them and pointing to this comment.

I will post an update comment here on anything that is done.

**Comment by pauby** [comment]
As a further update, I emailed the owner of this repository just now (email address in their profile). Hopefully, they will be able to provide additional information as they may not be the maintainers of the package, just the hosts of the source.

UPDATE: That didn't work. That email does not exist (translated from German):

> Message delivery failed to the following recipients or groups:
> 
> github@open-circle.ch
> The email address you entered could not be found. Check the recipient's email address and try sending the message again. If the problem persists, contact your email administrator.

I've gone to their website and sent a message through the Contact form.

**Comment by pauby** [comment]
I've had no updates on this from any of the contacts I made. Just as a final confirmation, I'm going to copy the files for the `adobereader` package tomorrow, bring this PR over and when it is ready, remove the other maintainers on the package and push a fixed version.

Hopefully, somebody will step in today and resolve this.

@aledeniz You appear to have a lot of experience with the package, so I would really appreciate getting help, and a thumbs up from you and @conitrade-as before I push it. I still hope we don't have to, however.

**Comment by aledeniz** [comment]
@pauby Just to confirm: I have tested this PR internally for the last two releases, and it has worked fine in hundreds of computers.
That said, we tend to keep all our estate at the latest version or close by, so this limits the version distribution of our target computers.

**Comment by pauby** [comment]
I've created a PR for this over at https://github.com/pauby/ChocoPackages/pull/183. I have a couple of tests I want to run and will then push the package once they are complete. That may be today or may be this weekend.

**Comment by pauby** [comment]
1. I've removed all the maintainers from the package, except myself.
2. I've pushed a [new version of the `adobereader`](https://community.chocolatey.org/packages/adobereader/2023.003.20215) package.
3. I asked for the Testing Exemption to be removed from the package, as that was no longer needed.
4. The PR over on my repository has been merged https://github.com/pauby/ChocoPackages/pull/183

If there are any issues with the package going forward, please raise an issue on my repository, until the package has a final home. Thanks to everybody here for being responsive and creating the PR and providing input.

I think this PR can now be closed as it's no longer needed.

**Comment by conitrade-as** [comment]
@pauby Thanks for taking the lead on this. I'll close this PR.

**Pull request closed without merging**
